export const someRecipies = [
      {
    id: "1",
    title: "Paneer Butter Masala",
    chef: "Vikas Khanna",
    category: "maincourse",
    description: "Creamy paneer curry with rich tomato and butter gravy.",
    ingredients: "Paneer, butter, tomato puree, cream, garam masala",
    instructions: "1. Cook masala base\n2. Add paneer & simmer\n3. Finish with cream.",
    cookingTime: 35,
    image: "https://vegecravings.com/wp-content/uploads/2017/04/paneer-butter-masala-recipe-step-by-step-instructions.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Veg Hakka Noodles",
    chef: "Sanjeev Kapoor",
    category: "maincourse",
    description: "Spicy Indo-Chinese stir-fried noodles with vegetables.",
    ingredients: "Noodles, carrots, cabbage, capsicum, soy sauce, garlic",
    instructions: "1. Boil noodles\n2. Stir-fry veggies\n3. Toss and serve.",
    cookingTime: 25,
    image: "https://www.creatable.de/wp-content/uploads/2024/12/Vegetable_Hakka_Noodles_Chaat.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Masala Dosa",
    chef: "Ranveer Brar",
    category: "maincourse",
    description: "South Indian crepe filled with spiced mashed potatoes.",
    ingredients: "Rice, urad dal, potatoes, curry leaves, mustard seeds",
    instructions: "1. Make dosa\n2. Stuff with potato\n3. Serve with chutney.",
    cookingTime: 30,
    image: "https://culinarydelightsandbeyond.com/wp-content/uploads/2023/03/dosa-5oF7d_hPJG4-scaled.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Chicken Manchurian",
    chef: "Harpal Sokhi",
    category: "maincourse",
    description: "Fried chicken balls in spicy garlic-soy sauce.",
    ingredients: "Chicken, garlic, spring onion, soy sauce, cornflour",
    instructions: "1. Fry chicken\n2. Make sauce\n3. Toss together.",
    cookingTime: 35,
    image: "https://img-global.cpcdn.com/recipes/edc51536e9baed70/1200x630cq70/photo.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Aloo Tikki Chaat",
    chef: "Nisha Madhulika",
    category: "snack",
    description: "Crispy potato patties topped with chutneys and yogurt.",
    ingredients: "Potatoes, tamarind chutney, green chutney, sev, curd",
    instructions: "1. Fry tikki\n2. Add toppings\n3. Serve fresh.",
    cookingTime: 20,
    image: "https://cdn.zeptonow.com/production/tr:w-600,ar-100-100,pr-true,f-auto,q-80/web/recipes/aloo-tikki-chaat.png",
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Pav Bhaji",
    chef: "Anand Stall",
    category: "maincourse",
    description: "Spiced mashed veggies with toasted buns.",
    ingredients: "Potatoes, capsicum, tomatoes, pav bhaji masala, butter",
    instructions: "1. Mash & cook veggies\n2. Toast pav\n3. Serve hot.",
    cookingTime: 30,
    image: "https://static.vecteezy.com/system/resources/previews/016/282/565/large_2x/cheese-pav-bhaji-recipe-is-a-street-food-bhaji-pav-recipe-with-addition-of-cheese-free-photo.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Tandoori Momos",
    chef: "Delhi Street Chef",
    category: "snack",
    description: "Momos tossed in tandoori masala & grilled.",
    ingredients: "Momos, yogurt, tandoori masala, cream",
    instructions: "1. Marinate momos\n2. Grill until charred.",
    cookingTime: 20,
    image: "https://nepalicookingclass.com/assets/images/foods/tandoori-momo.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Chole Bhature",
    chef: "Madhur Jaffrey",
    category: "maincourse",
    description: "Spiced chickpeas with fluffy fried bhature.",
    ingredients: "Chickpeas, tomatoes, flour, baking soda, masalas",
    instructions: "1. Make curry\n2. Fry bhature\n3. Serve hot.",
    cookingTime: 45,
    image: "https://t4.ftcdn.net/jpg/06/13/65/75/360_F_613657549_r41cG3xRcPuH4CUUGw3CFOHhHUnZXIOo.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    title: "Schezwan Fried Rice",
    chef: "The Bombay Chef",
    category: "maincourse",
    description: "Spicy Indo-Chinese fried rice with veggies & schezwan sauce.",
    ingredients: "Rice, spring onion, carrots, schezwan sauce, soy",
    instructions: "1. Stir fry veggies\n2. Add rice & sauce\n3. Serve hot.",
    cookingTime: 20,
    image: "https://img.freepik.com/premium-vector/veg-schezwan-fried-rice-illustration_953932-5151.jpg?w=740",
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    title: "Butter Chicken",
    chef: "Kunal Kapur",
    category: "maincourse",
    description: "Iconic creamy tomato chicken curry.",
    ingredients: "Chicken, tomato, cream, butter, kasuri methi",
    instructions: "1. Grill chicken\n2. Cook gravy\n3. Combine and serve.",
    cookingTime: 45,
    image: "https://simplychickenrecipe.com/wp-content/uploads/2022/10/All-About-Butter-Chicken.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "11",
    title: "Gulab Jamun",
    chef: "Tarla Dalal",
    category: "dessert",
    description: "Fried milk balls soaked in rose-scented syrup.",
    ingredients: "Khoya, flour, sugar, rose water",
    instructions: "1. Make dough\n2. Fry balls\n3. Dip in syrup.",
    cookingTime: 40,
    image: "https://img.freepik.com/premium-photo/tasty-gulab-jamuns-white-background_787273-3418.jpg?w=900",
    createdAt: new Date().toISOString(),
  },
  {
    id: "12",
    title: "Jaljeera",
    chef: "Ayurvedic Kitchen",
    category: "beverage",
    description: "Refreshing tangy-spicy summer drink.",
    ingredients: "Mint, cumin, tamarind, black salt, water",
    instructions: "1. Blend herbs & spices\n2. Mix with cold water.",
    cookingTime: 5,
    image: "https://www.ayurvedicindia.info/wp-content/uploads/Jaljeera%E0%A5%A4-Recipe-Powder-Health-Benefits-Explained.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "13",
    title: "Mango Lassi",
    chef: "Punjabi Dhaba",
    category: "beverage",
    description: "Creamy mango-yogurt smoothie with cardamom.",
    ingredients: "Mango, curd, sugar, cardamom",
    instructions: "1. Blend everything\n2. Serve chilled.",
    cookingTime: 5,
    image: "https://img.freepik.com/premium-photo/mango-lassi-refreshment_729149-8235.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "14",
    title: "Masala Chai",
    chef: "Local Chaiwala",
    category: "beverage",
    description: "Indian spiced tea made with milk, ginger, and cardamom.",
    ingredients: "Tea leaves, milk, ginger, cardamom, sugar",
    instructions: "1. Boil water with spices\n2. Add milk & tea\n3. Simmer & strain.",
    cookingTime: 10,
    image: "https://northernvirginiamag.com/wp-content/uploads/2024/01/chai-1.jpg",
    createdAt: new Date().toISOString(),
  },
  {
    id: "15",
    title: "Rasgulla",
    chef: "Bengali Sweets",
    category: "dessert",
    description: "Spongy milk balls in sugar syrup.",
    ingredients: "Chenna, sugar, water, cardamom",
    instructions: "1. Make chenna balls\n2. Boil in syrup\n3. Serve chilled.",
    cookingTime: 35,
    image: "https://img.freepik.com/premium-photo/picture-rasgulla_871710-37851.jpg",
    createdAt: new Date().toISOString(),
  }
]